config/routes.rb
OpenBeerDatabase::Application.routes.draw do
  constraints subdomain: "api" do
    namespace :v1, module: "Api::V1" do
      resources :beers,     only: [:index, :show, :create, :update, :destroy]
      resources :breweries, only: [:index, :show, :create, :update, :destroy]
    end
  end

  constraints subdomain: "www" do
    match "/*path" => redirect { |_, request| "http://#{request.host.sub("www.", "")}#{request.path}" }

    root to: redirect { |_, request| "http://#{request.host.sub("www.", "")}" }
  end

  constraints(lambda { |request| request.subdomain.blank? }) do
    resources :documentation, only: [:show]
    resource  :session,       only: [:new, :create]
    resources :users,         only: [:show, :new, :create]

    root to: "Documentation#show", id: "overview"
  end
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  SORTABLE_COLUMNS = %w(id name created_at updated_at).freeze

  include SearchableModel

  belongs_to :brewery
  belongs_to :user

  validates :brewery_id,  presence: true
  validates :name,        presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 4096 }
  validates :abv,         presence: true, numericality: true

  attr_accessible :name, :description, :abv

  def self.filter_by_brewery_id(brewery_id)
    if brewery_id.present?
      where(brewery_id: brewery_id)
    else
      where("")
    end
  end

  def self.search(options = {})
    includes(:brewery)
      .for_token(options[:token])
      .filter_by_name(options[:query])
      .filter_by_brewery_id(options[:brewery_id])
      .page(options[:page])
      .per_page(options[:per_page] || 50)
      .order_by(options[:order])
  end

  def public?
    user_id.nil?
  end
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  SORTABLE_COLUMNS = %w(id name created_at updated_at).freeze

  include SearchableModel

  has_many   :beers
  belongs_to :user

  validates :name, presence: true, length: { maximum: 255 }
  validates :url,  length: { maximum: 255 },
                   format: {
                     with:      %r{\Ahttps?://((([\w_]+\.)*)?[\w_]+([-.][\w_]+)*\.[a-z]{2,6}\.?)([/?]\S*)?\Z}i,
                     allow_nil: true
                   }

  attr_accessible :name, :url

  before_destroy :ensure_no_associated_beers_exist

  def self.search(options = {})
    for_token(options[:token])
      .filter_by_name(options[:query])
      .page(options[:page])
      .per_page(options[:per_page] || 50)
      .order_by(options[:order])
  end

  def public?
    user_id.nil?
  end

  private

  def ensure_no_associated_beers_exist
    beers.count == 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :beers
  has_many :breweries

  has_secure_password

  validates :name,  presence: true
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format:     { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :password,              presence: true, confirmation: true, if: :password_required?
  validates :password_confirmation, presence: true, if: :password_required?
  validates :public_token,          presence: true
  validates :private_token,         presence: true

  attr_accessible :name, :email, :password, :password_confirmation

  before_save       :clean_attributes
  before_validation :generate_tokens, on: :create

  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end

  def self.find_by_public_or_private_token(token)
    where("public_token = :token OR private_token = :token", token: token).first
  end

  def can_access?(record)
    record.respond_to?(:user) && (administrator? || record.user == self)
  end

  protected

  def clean_attributes
    email.downcase!
  end

  def generate_tokens
    self.public_token  ||= Digest::SHA256.hexdigest([Time.now.to_f, rand].join)
    self.private_token ||= Digest::SHA256.hexdigest([Time.now.to_f, rand].join)
  end

  def password_required?
    password_digest.blank? || password.present?
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  before_filter :authenticate,          only:   [:create, :update, :destroy]
  before_filter :validate_format,       except: [:destroy]
  before_filter :validate_query_length, only:   [:index]

  skip_before_filter :verify_authenticity_token

  rescue_from ActiveRecord::RecordNotFound do
    head :not_found
  end

  protected

  def access_denied
    head :unauthorized
  end

  def authorized_for?(record)
    (request.get? && record.public?) ||
      (signed_in? && current_user.can_access?(record))
  end

  def validate_format
    head(:not_acceptable) unless request.format.json?
  end

  def validate_query_length
    query = params[:query].to_s.strip

    if query.present? && query.length == 1
      head :bad_request
    end
  end
end

app/controllers/api/v1/beers_controller.rb
class Api::V1::BeersController < Api::V1::BaseController
  def index
    beers = Beer.search(params)

    render json: Api::V1::BeersPresenter.new(beers)
  end

  def show
    beer = Beer.find(params[:id])

    if params[:token].present?
      return head(:unauthorized) unless authorized_for?(beer)
    end

    render json: Api::V1::BeerPresenter.new(beer)
  end

  def create
    beer = current_user.beers.build(params[:beer])
    beer.brewery = current_user.breweries.find_by_id(params[:brewery_id])

    if beer.save
      head :created, location: v1_beer_url(beer, format: :json)
    else
      render json:   { errors: beer.errors },
             status: :bad_request
    end
  end

  def update
    beer = Beer.find(params[:id])

    if authorized_for?(beer)
      if beer.update_attributes(params[:beer])
        head :ok
      else
        render json:   { errors: beer.errors },
               status: :bad_request
      end
    else
      head :unauthorized
    end
  end

  def destroy
    beer = Beer.find(params[:id])

    if authorized_for?(beer)
      beer.destroy

      head :ok
    else
      head :unauthorized
    end
  end
end

app/controllers/api/v1/breweries_controller.rb
class Api::V1::BreweriesController < Api::V1::BaseController
  def index
    breweries = Brewery.search(params)

    render json: Api::V1::BreweriesPresenter.new(breweries)
  end

  def show
    brewery = Brewery.find(params[:id])

    if params[:token].present?
      return head(:unauthorized) unless authorized_for?(brewery)
    end

    render json: Api::V1::BreweryPresenter.new(brewery)
  end

  def create
    brewery = current_user.breweries.build(params[:brewery])

    if brewery.save
      head :created, location: v1_brewery_url(brewery, format: :json)
    else
      render json:   { errors: brewery.errors },
             status: :bad_request
    end
  end

  def update
    brewery = Brewery.find(params[:id])

    if authorized_for?(brewery)
      if brewery.update_attributes(params[:brewery])
        head :ok
      else
        render json:   { errors: brewery.errors },
               status: :bad_request
      end
    else
      head :unauthorized
    end
  end

  def destroy
    brewery = Brewery.find(params[:id])

    if authorized_for?(brewery)
      if brewery.destroy
        head :ok
      else
        head :bad_request
      end
    else
      head :unauthorized
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  protect_from_forgery
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
  def show
    render action: params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      self.current_user = user

      redirect_to user
    else
      redirect_to new_session_url, alert: "E-mail or password is incorrect. Please try again."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate,
                :find_user,
                :authorize, only: [:show]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user

      redirect_to user_url(@user)
    else
      render :new
    end
  end

  protected

  def authorize
    redirect_to(root_url) unless current_user == @user
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/documentation/beers-delete-id.html.erb
<header>
  <h1>DELETE /beers/:id</h1>
</header>

<p>Delete a beer from the database.</p>

<h2>Parameters</h2>

<p>All parameters are required.</p>

<table class="parameters">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>token</td>
      <td>string</td>
      <td>The API token of the user who created this beer. <span>Private only.</span></td>
    </tr>
  </tbody>
</table>

<h2>Errors</h2>

<table class="errors">
  <thead>
    <tr>
      <th>Status</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>401</td>
      <td>Unauthorized.</td>
    </tr>
    <tr>
      <td>404</td>
      <td>Not found.</td>
    </tr>
  </tbody>
</table>

<h2>Example</h2>

<div class="highlight"><pre><code>DELETE /v1/beers/<span class="variable">id</span>.json HTTP/1.1
Host: api.openbeerdatabase.com</code></pre>
</div>

<div class="highlight"><pre><code class="js">HTTP/1.1 200 OK</code></pre></div>

app/views/documentation/beers-get-id.html.erb
<header>
  <h1>GET /beers/:id</h1>
</header>

<p>Retrieve the details of a specific beer.</p>

<h2>Parameters</h2>

<p>All parameters are optional.</p>

<table class="parameters">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>callback</td>
      <td>string</td>
      <td>Name of the callback function for JSONP.</td>
    </tr>
    <tr>
      <td>token</td>
      <td>string</td>
      <td>The token of the API user who created the beer, if an API user created the beer. <span>Public or private.</span></td>
    </tr>
  </tbody>
</table>

<h2>Errors</h2>

<table class="errors">
  <thead>
    <tr>
      <th>Status</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>401</td>
      <td>Unauthorized.</td>
    </tr>
    <tr>
      <td>404</td>
      <td>Not found.</td>
    </tr>
    <tr>
      <td>406</td>
      <td>Invalid format.</td>
    </tr>
  </tbody>
</table>

<h2>Example</h2>

<div class="highlight"><pre><code>GET /v1/beers/<span class="variable">id</span>.json HTTP/1.1
Host: api.openbeerdatabase.com
Content-Type: application/json; charset=utf-8</code></pre>
</div>

<div class="highlight"><pre><code class="js">HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: <span class="variable">length</span>

<span class="p">{</span> <span class="s2">&#34;id&#34;</span>          <span class="o">:</span> <span class="variable">id</span><span class="p">,</span>
  <span class="s2">&#34;name&#34;</span>        <span class="o">:</span> <span class="s2">&#34;Strawberry Harvest&#34;</span><span class="p">,</span>
  <span class="s2">&#34;description&#34;</span> <span class="o">:</span> <span class="s2">&#34;Strawberry Harvest Lager is a wheat beer ...&#34;</span><span class="p">,</span>
  <span class="s2">&#34;abv&#34;</span>         <span class="o">:</span> <span class="mi">4.2</span><span class="p">,</span>
  <span class="s2">&#34;created_at&#34;</span>  <span class="o">:</span> <span class="s2">&#34;2010-01-01T00:00:00Z&#34;</span><span class="p">,</span>
  <span class="s2">&#34;updated_at&#34;</span>  <span class="o">:</span> <span class="s2">&#34;2010-02-02T12:30:00Z&#34;</span><span class="p">,</span>
  <span class="s2">&#34;brewery&#34;</span>     <span class="o">:</span> <span class="p">{</span>
    <span class="s2">&#34;id&#34;</span>   <span class="o">:</span> <span class="mi">1</span><span class="p">,</span>
    <span class="s2">&#34;name&#34;</span> <span class="o">:</span> <span class="s2">&#34;Abita&#34;</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre>
</div>

app/views/documentation/beers-get.html.erb
<header>
  <h1>GET /beers</h1>
</header>

<p>Retrieve the details of all beers, and narrow down the results with specific arguments.</p>

<h2>Parameters</h2>

<p>All parameters are optional.</p>

<table class="parameters">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>callback</td>
      <td>string</td>
      <td>Name of the callback function for JSONP.</td>
    </tr>
    <tr>
      <td>order</td>
      <td>string</td>
      <td>The order to sort the results by. <span>Defaults to &#8220;id ASC&#8221;. Valid options are &#8220;id&#8221;, &#8220;name&#8221;, &#8220;created_at&#8221;, and &#8220;updated_at&#8221; for the column and &#8220;ASC&#8221; and &#8220;DESC&#8221; for the direction.</td>
    </tr>
    <tr>
      <td>page</td>
      <td>integer</td>
      <td>The page of results to retrieve. <span>Defaults to &#8220;1&#8221;.</span></td>
    </tr>
    <tr>
      <td>per_page</td>
      <td>integer</td>
      <td>The number of results per page. <span>Defaults to &#8220;50&#8221;.</span></td>
    </tr>
    <tr>
      <td>query</td>
      <td>string</td>
      <td>The string to search with. <span>Case-insensitive and must be at least two characters. Automatically wrapped in wildcards, so a query of &#8220;kin&#8221; will find &#8220;Pumpking&#8221;.</span></td>
    </tr>
    <tr>
      <td>token</td>
      <td>string</td>
      <td>Include beers created by the API user with the specified token in the results. <span>Public or private.</span></td>
    </tr>
  </tbody>
</table>

<h2>Errors</h2>

<table class="errors">
  <thead>
    <tr>
      <th>Status</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>400</td>
      <td>Invalid query.</td>
    </tr>
    <tr>
      <td>406</td>
      <td>Invalid format.</td>
    </tr>
  </tbody>
</table>

<h2>Example</h2>

<div class="highlight"><pre><code>GET /v1/beers.json HTTP/1.1
Host: api.openbeerdatabase.com
Content-Type: application/json; charset=utf-8</code></pre>
</div>

<div class="highlight"><pre><code class="js">HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: <span class="variable">length</span>

<span class="p">{</span> <span class="s2">&#34;page&#34;</span>  <span class="o">:</span> <span class="mi">1</span><span class="p">,</span>
  <span class="s2">&#34;pages&#34;</span> <span class="o">:</span> <span class="mi">2</span><span class="p">,</span>
  <span class="s2">&#34;total&#34;</span> <span class="o">:</span> <span class="mi">55</span><span class="p">,</span>
  <span class="s2">&#34;beers&#34;</span> <span class="o">:</span> <span class="p">[</span>
    <span class="p">{</span> <span class="s2">&#34;id&#34;</span>          <span class="o">:</span> <span class="mi">1</span><span class="p">,</span>
      <span class="s2">&#34;name&#34;</span>        <span class="o">:</span> <span class="s2">&#34;Strawberry Harvest&#34;</span><span class="p">,</span>
      <span class="s2">&#34;description&#34;</span> <span class="o">:</span> <span class="s2">&#34;Strawberry Harvest Lager is a wheat beer ...&#34;</span><span class="p">,</span>
      <span class="s2">&#34;abv&#34;</span>         <span class="o">:</span> <span class="mi">4.2</span><span class="p">,</span>
      <span class="s2">&#34;created_at&#34;</span>  <span class="o">:</span> <span class="s2">&#34;2010-01-01T00:00:00Z&#34;</span><span class="p">,</span>
      <span class="s2">&#34;updated_at&#34;</span>  <span class="o">:</span> <span class="s2">&#34;2010-02-02T12:30:00Z&#34;</span><span class="p">,</span>
      <span class="s2">&#34;brewery&#34;</span>     <span class="o">:</span> <span class="p">{</span>
        <span class="s2">&#34;id&#34;</span>   <span class="o">:</span> <span class="mi">1</span><span class="p">,</span>
        <span class="s2">&#34;name&#34;</span> <span class="o">:</span> <span class="s2">&#34;Abita&#34;</span>
      <span class="p">}</span>
    <span class="p">},</span>
    <span class="p">...</span>
  <span class="p">]</span>
<span class="p">}</span>
</code></pre>
</div>

app/views/documentation/beers-post.html.erb
<header>
  <h1>POST /beers</h1>
</header>

<p>Create a new beer.</p>

<h2>Parameters</h2>

<p>All parameters are required.</p>

<table class="parameters">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>beer</td>
      <td>hash</td>
      <td>Attributes of the new beer.</td>
    </tr>
    <tr class="nested">
      <td>name</td>
      <td>string</td>
      <td>The name of the beer.</td>
    </tr>
    <tr class="nested">
      <td>description</td>
      <td>string</td>
      <td>The description of the beer.</td>
    </tr>
    <tr class="nested">
      <td>abv</td>
      <td>float</td>
      <td>The alcohol by volume of the beer.</td>
    </tr>
    <tr>
      <td>brewery_id</td>
      <td>integer</td>
      <td>The ID of the brewery to create a beer for.</td>
    </tr>
    <tr>
      <td>token</td>
      <td>string</td>
      <td>Token of the API user creating the beer. <span>Private only.</span></td>
    </tr>
  </tbody>
</table>

<h2>Errors</h2>

<table class="errors">
  <thead>
    <tr>
      <th>Status</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>400</td>
      <td>Invalid record. Responds with <a href="/documentation/errors">a JSON object containing errors</a>.</td>
    </tr>
    <tr>
      <td>401</td>
      <td>Unauthorized.</td>
    </tr>
    <tr>
      <td>406</td>
      <td>Invalid format.</td>
    </tr>
  </tbody>
</table>

<h2>Example</h2>

<div class="highlight"><pre><code class="js">POST /v1/beers.json HTTP/1.1
Host: api.openbeerdatabase.com
Content-Type: application/json; charset=utf-8
Content-Length: <span class="variable">length</span>

<span class="p">{</span> <span class="s2">&#34;brewery_id&#34;</span> <span class="o">:</span> <span class="mi">1</span><span class="p">,</span>
  <span class="s2">&#34;beer&#34;</span>       <span class="o">:</span> <span class="p">{</span>
    <span class="s2">&#34;name&#34;</span>        <span class="o">:</span> <span class="s2">&#34;Strawberry Harvest&#34;</span><span class="p">,</span>
    <span class="s2">&#34;description&#34;</span> <span class="o">:</span> <span class="s2">&#34;Strawberry Harvest Lager is a wheat beer ...&#34;</span><span class="p">,</span>
    <span class="s2">&#34;abv&#34;</span>         <span class="o">:</span> <span class="mi">4.2</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre>
</div>

<div class="highlight"><pre><code>HTTP/1.1 201 Created
Location: http://api.openbeerdatabase.com/v1/beers/<span class="variable">id</span>.json</code></pre>
</div>

app/views/documentation/beers-put-id.html.erb
<header>
  <h1>PUT /beers/:id</h1>
</header>

<p>Updates an existing beer.</p>

<h2>Parameters</h2>

<p>All parameters, except token, are optional.</p>

<table class="parameters">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>beer</td>
      <td>hash</td>
      <td>Attributes to update on the beer.</td>
    </tr>
    <tr class="nested">
      <td>name</td>
      <td>string</td>
      <td>The name of the beer.</td>
    </tr>
    <tr class="nested">
      <td>description</td>
      <td>string</td>
      <td>The description of the beer.</td>
    </tr>
    <tr class="nested">
      <td>abv</td>
      <td>float</td>
      <td>The alcohol by volume of the beer.</td>
    </tr>
    <tr>
      <td>token</td>
      <td>string</td>
      <td>The API token of the user who created this beer. <span>Private only.</span></td>
    </tr>
  </tbody>
</table>

<h2>Errors</h2>

<table class="errors">
  <thead>
    <tr>
      <th>Status</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>400</td>
      <td>Invalid record. Responds with <a href="/documentation/errors">a JSON object containing errors</a>.</td>
    </tr>
    <tr>
      <td>401</td>
      <td>Unauthorized.</td>
    </tr>
    <tr>
      <td>404</td>
      <td>Not found.</td>
    </tr>
    <tr>
      <td>406</td>
      <td>Invalid format.</td>
    </tr>
  </tbody>
</table>

<h2>Example</h2>

<div class="highlight"><pre><code class="js">PUT /v1/beers/<span class="variable">id</span>.json HTTP/1.1
Host: api.openbeerdatabase.com
Content-Type: application/json; charset=utf-8
Content-Length: <span class="variable">length</span>

<span class="p">{</span> <span class="s2">&#34;beer&#34;</span> <span class="o">:</span> <span class="p">{</span>
    <span class="s2">&#34;name&#34;</span>        <span class="o">:</span> <span class="s2">&#34;Strawberry Harvest&#34;</span><span class="p">,</span>
    <span class="s2">&#34;description&#34;</span> <span class="o">:</span> <span class="s2">&#34;Strawberry Harvest Lager is a wheat beer ...&#34;</span><span class="p">,</span>
    <span class="s2">&#34;abv&#34;</span>         <span class="o">:</span> <span class="mi">4.2</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre>
</div>

<div class="highlight"><pre><code>HTTP/1.1 200 OK</code></pre></div>

app/views/documentation/breweries-delete-id.html.erb
<header>
  <h1>DELETE /breweries/:id</h1>
</header>

<p>Delete a brewery from the database. The brewery may only be deleted if it has zero beers.</p>

<h2>Parameters</h2>

<p>All parameters are required.</p>

<table class="parameters">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>token</td>
      <td>string</td>
      <td>The API token of the user who created this brewery. <span>Private only.</span></td>
    </tr>
  </tbody>
</table>

<h2>Errors</h2>

<table class="errors">
  <thead>
    <tr>
      <th>Status</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>400</td>
      <td>Does not have zero beers.</td>
    </tr>
    <tr>
      <td>401</td>
      <td>Unauthorized.</td>
    </tr>
    <tr>
      <td>404</td>
      <td>Not found.</td>
    </tr>
  </tbody>
</table>

  </tbody>
</table>

<h2>Example</h2>

<div class="highlight"><pre><code>DELETE /v1/breweries/<span class="variable">id</span>.json HTTP/1.1
Host: api.openbeerdatabase.com</code></pre>
</div>

<div class="highlight"><pre><code class="js">HTTP/1.1 200 OK</code></pre></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="utf-8">

  <title>Open Beer Database</title>

  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Arvo:bold&subset=latin" %>
  <%= stylesheet_link_tag "application" %>

  <% unless %w(development test).include?(Rails.env) -%>
  <script>
    var _gaq = _gaq || [];
    _gaq.push(["_setAccount", "UA-8648594-10"]);
    _gaq.push(["_trackPageview"]);

    (function() {
      var ga = document.createElement("script"); ga.type = "text/javascript"; ga.async = true;
      ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";
      var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <% end -%>
</head>
<body>

<header>
  <div class="container">
    <h1><a href="/"><span>O</span>p<span>e</span>n <span>B</span>e<span>e</span>r <span>D</span><span>a</span><span>t</span><span>a</span><span>b</span><span>a</span>se</a></h1>
    <h2>A free, public database and API for beer information.</h2>

    <% if signed_in? %>
      <p id="current-user">Signed in as <%= link_to current_user.name, current_user %>.</p>
    <% else %>
      <p id="sign-up"><%= link_to "Sign up for an API token.", new_user_path %></p>
      <p id="sign-in">Already have an account? <%= link_to "Sign in", new_session_path %>.</p>
    <% end %>
  </div>
</header>

<section class="container">
  <section>
    <% if flash[:alert].present? %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end -%>

    <%= yield %>
  </section>

  <aside>
    <header>
      <h1>Version 1.0</h1>
    </header>

    <dl>
      <dt>Beers</dt>
      <dd>
        <ul>
          <li><a href="/documentation/beers-get"><span>GET</span> /beers</a></li>
          <li><a href="/documentation/beers-get-id"><span>GET</span> /beers/:id</a></li>
          <li><a href="/documentation/beers-post"><span>POST</span> /beers</a></li>
          <li><a href="/documentation/beers-put-id"><span>PUT</span> /beers/:id</a></li>
          <li><a href="/documentation/beers-delete-id"><span>DELETE</span> /beers/:id</a></li>
        </ul>
      </dd>
      <dt>Breweries</dt>
      <dd>
        <ul>
          <li><a href="/documentation/breweries-get"><span>GET</span> /breweries</a></li>
          <li><a href="/documentation/breweries-get-id"><span>GET</span> /breweries/:id</a></li>
          <li><a href="/documentation/breweries-post"><span>POST</span> /breweries</a></li>
          <li><a href="/documentation/breweries-put-id"><span>PUT</span> /breweries/:id</a></li>
          <li><a href="/documentation/breweries-delete-id"><span>DELETE</span> /breweries/:id</a></li>
        </ul>
      </dd>
    </dl>

    <header>
      <h1>Examples</h1>
    </header>

    <ul>
      <li><a href="/documentation/examples-jsonp">Displaying breweries via JSONP.</a></li>
    </ul>

    <header>
      <h1>Libraries</h1>
    </header>

    <ul>
      <li><a href="https://rubygems.org/gems/bartender">Bartender</a> &#8212; Ruby</li>
      <li><a href="https://github.com/h0ke/phuggles">Phuggles</a> &#8212; PHP</li>
      <li><a href="https://github.com/h0ke/pynt">Pynt</a> &#8212; Python</li>
    </ul>
  </aside>
</section>

<footer class="container">
  <p class="license">Database made available under the <a href="http://opendatacommons.org/licenses/pddl/summary/">Public Domain Dedication and License v1.0</a>.</p>
  <p><a href="https://github.com/openbeerdatabase/openbeerdatabase">Fork me</a> on GitHub.</p>
  <p>Follow <a href="http://twitter.com/beerdatabase">@beerdatabase</a> on Twitter.</p>
</footer>

<%= yield :javascript %>

</body>
</html>